#!/bin/sh
#
# git post-checkout hook, used by propellor's author to maintain a
# joeyconfig branch where config.hs is a symlink to joeyconfig.hs
#
# Each time this hook is run, it checks if it's on a branch with
# name ending in "config". If so, config.hs is pointed at $branch.hs
# Otherwise, config.hs is pointed at config-simple.hs
#

set -e
prevhead="$1"
newhead="$2"
branchcheckout="$3"
if [ "$branchcheckout" != 0 ]; then
	branch="$(git symbolic-ref --short HEAD)"
	case "$branch" in
		"")
			true
			;;
		*config)
			ln -sf "$branch".hs config.hs
			;;
		*)
			ln -sf config-simple.hs config.hs
			;;
	esac
fi
